"""Create and manage pull requests on GitHub."""

import logging
import subprocess
from dataclasses import dataclass, field

from github import GithubException

from reknew.config import ReknewConfig
from reknew.github.api import GitHubAPI

logger = logging.getLogger(__name__)


@dataclass
class PRResult:
    """Result of creating a pull request."""

    pr_number: int
    pr_url: str
    branch: str
    title: str


@dataclass
class CIStatus:
    """CI status for a pull request."""

    overall: str  # "passed", "failed", "pending"
    checks: list[dict] = field(default_factory=list)
    failed_checks: list[dict] = field(default_factory=list)


@dataclass
class ReviewComment:
    """A single review comment on a PR."""

    reviewer: str
    body: str
    state: str  # "APPROVED", "CHANGES_REQUESTED", "COMMENTED"
    path: str | None = None
    line: int | None = None
    created_at: str = ""


class PRManager:
    """Creates PRs and monitors their status on GitHub."""

    def __init__(self, github_api: GitHubAPI, config: ReknewConfig):
        """Initialize.

        Args:
            github_api: GitHubAPI instance for API access
            config: validated ReknewConfig
        """
        self.api = github_api
        self.config = config

    def push_branch(self, repo_path: str, branch: str) -> None:
        """Push a local branch to GitHub origin.

        Only the daemon calls this -- agents never push.

        Steps:
        1. git push origin {branch}
        2. If push fails (remote branch exists), force push with lease

        Args:
            repo_path: local path to the git repo
            branch: branch name to push

        Raises:
            subprocess.CalledProcessError: if push fails
        """
        result = subprocess.run(
            ["git", "push", "origin", branch],
            cwd=repo_path,
            capture_output=True,
            text=True,
        )
        if result.returncode != 0:
            logger.warning("Push failed, trying force-with-lease: %s",
                           result.stderr.strip())
            subprocess.run(
                ["git", "push", "--force-with-lease", "origin", branch],
                cwd=repo_path,
                check=True,
                capture_output=True,
                text=True,
            )

    def create_pr(
        self,
        repo_name: str,
        branch: str,
        base: str,
        title: str,
        body: str,
        task_id: str,
        issue_number: int | None = None,
    ) -> PRResult:
        """Create a pull request on GitHub.

        Args:
            repo_name: "owner/repo" format
            branch: head branch
            base: base branch (e.g. "main")
            title: PR title (prefix will be prepended)
            body: PR body markdown
            task_id: the ReKnew task identifier
            issue_number: optional linked GitHub issue number

        Returns:
            PRResult with pr_number and url

        Raises:
            GithubException: if PR creation fails
        """
        prefix = self.config.github.pr_prefix
        pr_title = f"{prefix} {title}"

        pr_body_parts = [f"**Task:** {task_id}\n"]
        if issue_number:
            pr_body_parts.append(f"**Issue:** #{issue_number}\n")
        pr_body_parts.append(body)
        pr_body_parts.append(
            "\n---\n*Generated by ReKnew AI-SDLC pipeline*"
        )
        pr_body = "\n".join(pr_body_parts)

        repo = self.api.get_repo(repo_name)
        pr = repo.create_pull(
            title=pr_title,
            body=pr_body,
            head=branch,
            base=base,
        )

        if self.config.github.auto_label_prs:
            try:
                pr.add_to_labels("reknew-ai")
            except GithubException:
                logger.warning("Could not add 'reknew-ai' label to PR #%d",
                               pr.number)

        logger.info("Created PR #%d: %s", pr.number, pr.html_url)
        return PRResult(
            pr_number=pr.number,
            pr_url=pr.html_url,
            branch=branch,
            title=pr_title,
        )

    def get_ci_status(self, repo_name: str, pr_number: int) -> CIStatus:
        """Check CI status on a PR.

        Combines GitHub Status API and Check Runs API.

        Args:
            repo_name: "owner/repo" format
            pr_number: the GitHub PR number

        Returns:
            CIStatus with overall and per-check details
        """
        pr = self.api.get_pull(repo_name, pr_number)
        head_sha = pr.head.sha
        repo = self.api.get_repo(repo_name)
        commit = repo.get_commit(head_sha)

        checks: list[dict] = []

        # Check Runs (GitHub Actions)
        for run in commit.get_check_runs():
            entry = {
                "name": run.name,
                "state": self._map_check_conclusion(run.conclusion),
                "description": run.output.get("summary", "") if run.output else "",
                "url": run.html_url,
            }
            checks.append(entry)

        # Commit Statuses (older CI systems)
        for status in commit.get_statuses():
            entry = {
                "name": status.context,
                "state": self._map_status_state(status.state),
                "description": status.description or "",
                "url": status.target_url or "",
            }
            checks.append(entry)

        failed = [c for c in checks if c["state"] == "failure"]

        if failed:
            overall = "failed"
        elif all(c["state"] == "success" for c in checks) and checks:
            overall = "passed"
        else:
            overall = "pending"

        return CIStatus(overall=overall, checks=checks, failed_checks=failed)

    def get_review_comments(
        self, repo_name: str, pr_number: int
    ) -> list[ReviewComment]:
        """Get review comments requesting changes.

        Only returns comments from CHANGES_REQUESTED reviews
        and any inline comments.

        Args:
            repo_name: "owner/repo" format
            pr_number: the GitHub PR number

        Returns:
            list of ReviewComment objects
        """
        pr = self.api.get_pull(repo_name, pr_number)
        comments: list[ReviewComment] = []

        for review in pr.get_reviews():
            if review.state in ("CHANGES_REQUESTED", "COMMENTED"):
                if review.body:
                    comments.append(ReviewComment(
                        reviewer=review.user.login,
                        body=review.body,
                        state=review.state,
                        path=None,
                        line=None,
                        created_at=str(review.submitted_at),
                    ))

        for rc in pr.get_review_comments():
            comments.append(ReviewComment(
                reviewer=rc.user.login,
                body=rc.body,
                state="INLINE",
                path=rc.path,
                line=rc.original_line,
                created_at=str(rc.created_at),
            ))

        return comments

    def merge_pr(
        self, repo_name: str, pr_number: int, method: str = "squash"
    ) -> bool:
        """Merge a PR via GitHub API.

        Args:
            repo_name: "owner/repo" format
            pr_number: PR number
            method: "merge", "squash", or "rebase"

        Returns:
            True if merged, False if merge failed
        """
        try:
            pr = self.api.get_pull(repo_name, pr_number)
            pr.merge(merge_method=method)
            logger.info("Merged PR #%d via %s", pr_number, method)
            return True
        except GithubException as exc:
            logger.error("Failed to merge PR #%d: %s", pr_number, exc)
            return False

    def close_pr(
        self, repo_name: str, pr_number: int, comment: str = ""
    ) -> None:
        """Close a PR without merging.

        Args:
            repo_name: "owner/repo" format
            pr_number: PR number
            comment: optional closing comment
        """
        pr = self.api.get_pull(repo_name, pr_number)
        if comment:
            pr.create_issue_comment(comment)
        pr.edit(state="closed")
        logger.info("Closed PR #%d", pr_number)

    def format_ci_errors(self, ci_status: CIStatus) -> str:
        """Format CI failure details into a prompt for the agent.

        Args:
            ci_status: CIStatus with failed checks

        Returns:
            Formatted string describing failures
        """
        lines = [
            "CI failed on your PR. Please fix the following errors:\n"
        ]
        for check in ci_status.failed_checks:
            lines.append(f"X Check: \"{check['name']}\"")
            lines.append(f"  Status: {check['state']}")
            if check.get("description"):
                lines.append(f"  Details: {check['description']}")
            if check.get("url"):
                lines.append(f"  Log URL: {check['url']}")
            lines.append("")
        lines.append(
            "Please fix these issues, commit, and push. "
            "The CI will re-run automatically."
        )
        return "\n".join(lines)

    def format_review_comments(
        self, comments: list[ReviewComment]
    ) -> str:
        """Format review comments into a prompt for the agent.

        Args:
            comments: list of ReviewComment objects

        Returns:
            Formatted string for agent consumption
        """
        lines = [
            "Code review requested changes on your PR. "
            "Please address:\n"
        ]
        for c in comments:
            location = ""
            if c.path:
                location = f" (on {c.path}"
                if c.line:
                    location += f", line {c.line}"
                location += ")"
            lines.append(f"Reviewer: {c.reviewer}{location}")
            lines.append(f"  Comment: \"{c.body}\"")
            lines.append("")
        lines.append("Please address all comments, commit, and push.")
        return "\n".join(lines)

    @staticmethod
    def _map_check_conclusion(conclusion: str | None) -> str:
        """Map GitHub Check Run conclusion to simple state."""
        if conclusion is None:
            return "pending"
        return {
            "success": "success",
            "failure": "failure",
            "neutral": "success",
            "cancelled": "failure",
            "timed_out": "failure",
            "action_required": "pending",
            "skipped": "success",
        }.get(conclusion, "pending")

    @staticmethod
    def _map_status_state(state: str) -> str:
        """Map GitHub commit status state to simple state."""
        return {
            "success": "success",
            "failure": "failure",
            "error": "failure",
            "pending": "pending",
        }.get(state, "pending")
